=== mrsops/ProyectoXML/DocumentoXml/instalaciones_deportivas.dtd
<?xml version='1.0' encoding='UTF-8'?>

        <!--
            TODO define vocabulary identification
            PUBLIC ID: -//vendor//vocabulary//EN
            SYSTEM ID: http://server/path/instalaciones_deportivas.dtd

        -->

        <!--
            An example how to use this DTD from your XML document:

            <?xml version="1.0"?>

            <!DOCTYPE instalaciones-deportivas SYSTEM "instalaciones_deportivas.dtd">

            <instalaciones-deportivas>
            ...
            </instalaciones-deportivas>
        -->

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT instalaciones-deportivas (instalacion)*>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT instalacion (id|pedania|lugar|longitud|latitud|tipo-instalacion|barrio)*>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT id (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT pedania (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT lugar (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT longitud (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT latitud (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT tipo-instalacion (idubicacion|uso|cantidad)*>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT idubicacion (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT uso (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT cantidad (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT barrio (#PCDATA)>

=== mrsops/ProyectoXML/DocumentoXml/instalaciones_deportivas.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE instalaciones-deportivas SYSTEM "instalaciones_deportivas.dtd">
<instalaciones-deportivas>
    <instalacion>
        <id>1</id>
        <pedania>CAZALLA</pedania>
        <lugar>Centro de capacitación agraria</lugar>
        <longitud>-1.6872167587280273</longitud>
        <latitud>37.654245892818686</latitud>
        <tipo-instalacion>
            <idubicacion>1</idubicacion>
            <uso>Vestuario</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>1</idubicacion>
            <uso>Fútbol 7</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>1</idubicacion>
            <uso>Pista polideportiva</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>49</id>
        <pedania>ALMENDRICOS</pedania>
        <lugar>Afueras del casco de Almendricos</lugar>
        <longitud>-1.7760944366455078</longitud>
        <latitud>37.46439394507928</latitud>
        <tipo-instalacion>
            <idubicacion>49</idubicacion>
            <uso>Vestuario</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>49</idubicacion>
            <uso>Fútbol</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>33</id>
        <pedania>PURIAS</pedania>
        <lugar>Colegio de Purias</lugar>
        <longitud>-1.6713166236877441</longitud>
        <latitud>37.577041285970068</latitud>
        <tipo-instalacion>
            <idubicacion>33</idubicacion>
            <uso>Vestuario</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>33</idubicacion>
            <uso>Pista de tamaño reducido</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>33</idubicacion>
            <uso>Pista polideportiva múltiple</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>2</id>
        <pedania>PULGARA</pedania>
        <lugar>AAVV Pulgara</lugar>
        <longitud>-1.681208610534668</longitud>
        <latitud>37.66857054857509</latitud>
        <tipo-instalacion>
            <idubicacion>2</idubicacion>
            <uso>Pista de tamaño reducido</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>65</id>
        <pedania>PACA (LA)</pedania>
        <lugar>Colegio de La Paca</lugar>
        <longitud>-1.8343734741210938</longitud>
        <latitud>37.8684022326721</latitud>
        <tipo-instalacion>
            <idubicacion>65</idubicacion>
            <uso>Vestuario</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>65</idubicacion>
            <uso>Pista polideportiva</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>72</id>
        <pedania>ALMENDRICOS</pedania>
        <lugar>Junto colegio nuevo de Almendricos</lugar>
        <longitud>-1.7767274379730225</longitud>
        <latitud>37.469234497023429</latitud>
        <tipo-instalacion>
            <idubicacion>72</idubicacion>
            <uso>Modulo escolar nivel 3 (bm y vestuarios)</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>7</id>
        <barrio>SUTULLENA</barrio>
        <lugar>Colegio Muñoz Barberán</lugar>
        <longitud>-1.6951212286949158</longitud>
        <latitud>37.669482558423176</latitud>
        <tipo-instalacion>
            <idubicacion>7</idubicacion>
            <uso>Pista de tamaño reducido</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>10</id>
        <pedania>TOVA (LA)</pedania>
        <lugar>Colegio de La Tova</lugar>
        <longitud>-1.8978989124298096</longitud>
        <latitud>37.728591849038942</latitud>
        <tipo-instalacion>
            <idubicacion>10</idubicacion>
            <uso>Pista polideportiva</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>9</id>
        <barrio>ANGELES (LOS)-APOLONIA</barrio>
        <lugar>Parque de Los Angeles</lugar>
        <longitud>-1.6815733909606934</longitud>
        <latitud>37.685438329494495</latitud>
        <tipo-instalacion>
            <idubicacion>9</idubicacion>
            <uso>Vestuario</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>9</idubicacion>
            <uso>Fútbol 7</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>20</id>
        <pedania>AVILES</pedania>
        <lugar>Colegio de Avilés</lugar>
        <longitud>-1.801385321832754</longitud>
        <latitud>37.907906693461321</latitud>
        <tipo-instalacion>
            <idubicacion>20</idubicacion>
            <uso>Pista polideportiva</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>11</id>
        <barrio>SAN CRISTOBAL</barrio>
        <lugar>Parque San Diego</lugar>
        <longitud>-1.6923880577087402</longitud>
        <latitud>37.679851320896304</latitud>
        <tipo-instalacion>
            <idubicacion>11</idubicacion>
            <uso>Pista polideportiva múltiple</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>11</idubicacion>
            <uso>Pista de petanca</uso>
            <cantidad>12</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>12</id>
        <barrio>SUTULLENA</barrio>
        <lugar>Colegio José Robles</lugar>
        <longitud>-1.6949307918548584</longitud>
        <latitud>37.668873226154581</latitud>
        <tipo-instalacion>
            <idubicacion>12</idubicacion>
            <uso>Pista polideportiva</uso>
            <cantidad>2</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>13</id>
        <pedania>BEJAR</pedania>
        <lugar>Polígono industrial de Lorca</lugar>
        <longitud>-1.7613744735717773</longitud>
        <latitud>37.61600868889353</latitud>
        <tipo-instalacion>
            <idubicacion>13</idubicacion>
            <uso>Vestuario</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>13</idubicacion>
            <uso>Fútbol</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>14</id>
        <pedania>RAMONETE</pedania>
        <lugar>Las Librilleras</lugar>
        <longitud>-1.4540362358093262</longitud>
        <latitud>37.535058808569751</latitud>
        <tipo-instalacion>
            <idubicacion>14</idubicacion>
            <uso>Vestuario</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>14</idubicacion>
            <uso>Pista polideportiva</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>27</id>
        <barrio>SAN JOSE</barrio>
        <lugar>Subida al Calvario</lugar>
        <longitud>-1.7043131589889526</longitud>
        <latitud>37.671981405328125</latitud>
        <tipo-instalacion>
            <idubicacion>27</idubicacion>
            <uso>Vestuario</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>27</idubicacion>
            <uso>Pista polideportiva</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>8</id>
        <pedania>COY</pedania>
        <lugar>Colegio de Coy</lugar>
        <longitud>-1.8129962682724</longitud>
        <latitud>37.949530033303311</latitud>
        <tipo-instalacion>
            <idubicacion>8</idubicacion>
            <uso>Pista de tamaño reducido</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>16</id>
        <barrio>SAN CRISTOBAL</barrio>
        <lugar>Alfonso Embarre</lugar>
        <longitud>-1.6902637481689453</longitud>
        <latitud>37.68761666059325</latitud>
        <tipo-instalacion>
            <idubicacion>16</idubicacion>
            <uso>Vestuario</uso>
            <cantidad>2</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>16</idubicacion>
            <uso>Fútbol</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>16</idubicacion>
            <uso>Fútbol 7</uso>
            <cantidad>2</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>17</id>
        <barrio>SAN ANTONIO</barrio>
        <lugar>Parque de San Antonio</lugar>
        <longitud>-1.712418794631958</longitud>
        <latitud>37.65726125278001</latitud>
        <tipo-instalacion>
            <idubicacion>17</idubicacion>
            <uso>Fútbol 7</uso>
            <cantidad>1</cantidad>
        </tipo-instalacion>
        <tipo-instalacion>
            <idubicacion>17</idubicacion>
            <uso>Pista de petanca</uso>
            <cantidad>4</cantidad>
        </tipo-instalacion>
    </instalacion>
    <instalacion>
        <id>18</id>
        <barrio>SAN ANTONIO</barrio>
        <lugar>I.E.S. San Juan Bosco</lugar>
        <longitud>-1.7114344239234924</longitud>
